name: SimplePerms
author: Borane#9999
version: 1.0.0
main: fr.borane.simpleperms.Main

commands:
  promote:
    name: Promote
    description: Promote an user
    permission: simpleperms.promote
  demote:
    name: Demote
    description: Demote an user
    permission: simpleperms.demote
  user:
    name: User
    description: Manage an user
    permission: simpleperms.user